// Copyright (c) 2010 Satoshi Nakamoto
// Copyright (c) 2009-2017 The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <base58.h>
#include <bill.h>
#include <gramscale.h>
#include <house.h>
#include <pool.h>
#include <note.h>
#include <bmmcache.h>
#include <chain.h>
#include <clientversion.h>
#include <core_io.h>
#include <crypto/ripemd160.h>
#include <init.h>
#include <validation.h>
#include <httpserver.h>
#include <net.h>
#include <netbase.h>
#include <rpc/blockchain.h>
#include <rpc/server.h>
#include <rpc/util.h>
#include <sidechain.h>
#include <sidechainclient.h>
#include <timedata.h>
#include <txdb.h>
#include <util.h>
#include <utilstrencodings.h>
#ifdef ENABLE_WALLET
#include <wallet/rpcwallet.h>
#include <wallet/wallet.h>
#include <wallet/walletdb.h>
#endif
#include <warnings.h>

#include <stdint.h>
#ifdef HAVE_MALLOC_INFO
#include <malloc.h>
#endif

#include <univalue.h>

UniValue validateaddress(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "validateaddress \"address\"\n"
            "\nReturn information about the given bitcoin address.\n"
            "DEPRECATION WARNING: Parts of this command have been deprecated and moved to getaddressinfo. Clients must\n"
            "transition to using getaddressinfo to access this information before upgrading to v0.18. The following deprecated\n"
            "fields have moved to getaddressinfo and will only be shown here with -deprecatedrpc=validateaddress: ismine, iswatchonly,\n"
            "script, hex, pubkeys, sigsrequired, pubkey, addresses, embedded, iscompressed, account, timestamp, hdkeypath, kdmasterkeyid.\n"
            "\nArguments:\n"
            "1. \"address\"                    (string, required) The bitcoin address to validate\n"
            "\nResult:\n"
            "{\n"
            "  \"isvalid\" : true|false,       (boolean) If the address is valid or not. If not, this is the only property returned.\n"
            "  \"address\" : \"address\",        (string) The bitcoin address validated\n"
            "  \"scriptPubKey\" : \"hex\",       (string) The hex encoded scriptPubKey generated by the address\n"
            "  \"isscript\" : true|false,      (boolean) If the key is a script\n"
            "  \"iswitness\" : true|false,     (boolean) If the address is a witness address\n"
            "  \"witness_version\" : version   (numeric, optional) The version number of the witness program\n"
            "  \"witness_program\" : \"hex\"     (string, optional) The hex value of the witness program\n"
            "}\n"
            "\nExamples:\n"
            + HelpExampleCli("validateaddress", "\"1PSSGeFHDnKNxiEyFrD1wcEaHr9hrQDDWc\"")
            + HelpExampleRpc("validateaddress", "\"1PSSGeFHDnKNxiEyFrD1wcEaHr9hrQDDWc\"")
        );

    CTxDestination dest = DecodeDestination(request.params[0].get_str());
    bool isValid = IsValidDestination(dest);

    UniValue ret(UniValue::VOBJ);
    ret.pushKV("isvalid", isValid);
    if (isValid)
    {

#ifdef ENABLE_WALLET
        if (!::vpwallets.empty() && IsDeprecatedRPCEnabled("validateaddress")) {
            ret.pushKVs(getaddressinfo(request));
        }
#endif
        if (ret["address"].isNull()) {
            std::string currentAddress = EncodeDestination(dest);
            ret.pushKV("address", currentAddress);

            CScript scriptPubKey = GetScriptForDestination(dest);
            ret.pushKV("scriptPubKey", HexStr(scriptPubKey.begin(), scriptPubKey.end()));;

            UniValue detail = DescribeAddress(dest);
            ret.pushKVs(detail);
        }
    }
    return ret;
}

// Needed even with !ENABLE_WALLET, to pass (ignored) pointers around
class CWallet;

UniValue createmultisig(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() < 2 || request.params.size() > 2)
    {
        std::string msg = "createmultisig nrequired [\"key\",...]\n"
            "\nCreates a multi-signature address with n signature of m keys required.\n"
            "It returns a json object with the address and redeemScript.\n"
            "\nArguments:\n"
            "1. nrequired                    (numeric, required) The number of required signatures out of the n keys.\n"
            "2. \"keys\"                       (string, required) A json array of hex-encoded public keys\n"
            "     [\n"
            "       \"key\"                    (string) The hex-encoded public key\n"
            "       ,...\n"
            "     ]\n"

            "\nResult:\n"
            "{\n"
            "  \"address\":\"multisigaddress\",  (string) The value of the new multisig address.\n"
            "  \"redeemScript\":\"script\"       (string) The string value of the hex-encoded redemption script.\n"
            "}\n"

            "\nExamples:\n"
            "\nCreate a multisig address from 2 public keys\n"
            + HelpExampleCli("createmultisig", "2 \"[\\\"03789ed0bb717d88f7d321a368d905e7430207ebbd82bd342cf11ae157a7ace5fd\\\",\\\"03dbc6764b8884a92e871274b87583e6d5c2a58819473e17e107ef3f6aa5a61626\\\"]\"") +
            "\nAs a json rpc call\n"
            + HelpExampleRpc("createmultisig", "2, \"[\\\"03789ed0bb717d88f7d321a368d905e7430207ebbd82bd342cf11ae157a7ace5fd\\\",\\\"03dbc6764b8884a92e871274b87583e6d5c2a58819473e17e107ef3f6aa5a61626\\\"]\"")
        ;
        throw std::runtime_error(msg);
    }

    int required = request.params[0].get_int();

    // Get the public keys
    const UniValue& keys = request.params[1].get_array();
    std::vector<CPubKey> pubkeys;
    for (unsigned int i = 0; i < keys.size(); ++i) {
        if (IsHex(keys[i].get_str()) && (keys[i].get_str().length() == 66 || keys[i].get_str().length() == 130)) {
            pubkeys.push_back(HexToPubKey(keys[i].get_str()));
        } else {
            throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, strprintf("Invalid public key: %s\nNote that from v0.16, createmultisig no longer accepts addresses."
            " Users must use addmultisigaddress to create multisig addresses with addresses known to the wallet.", keys[i].get_str()));
        }
    }

    // Construct using pay-to-script-hash:
    CScript inner = CreateMultisigRedeemscript(required, pubkeys);
    CScriptID innerID(inner);

    UniValue result(UniValue::VOBJ);
    result.pushKV("address", EncodeDestination(innerID));
    result.pushKV("redeemScript", HexStr(inner.begin(), inner.end()));

    return result;
}

UniValue verifymessage(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 3)
        throw std::runtime_error(
            "verifymessage \"address\" \"signature\" \"message\"\n"
            "\nVerify a signed message\n"
            "\nArguments:\n"
            "1. \"address\"         (string, required) The bitcoin address to use for the signature.\n"
            "2. \"signature\"       (string, required) The signature provided by the signer in base 64 encoding (see signmessage).\n"
            "3. \"message\"         (string, required) The message that was signed.\n"
            "\nResult:\n"
            "true|false   (boolean) If the signature is verified or not.\n"
            "\nExamples:\n"
            "\nUnlock the wallet for 30 seconds\n"
            + HelpExampleCli("walletpassphrase", "\"mypassphrase\" 30") +
            "\nCreate the signature\n"
            + HelpExampleCli("signmessage", "\"1D1ZrZNe3JUo7ZycKEYQQiQAWd9y54F4XX\" \"my message\"") +
            "\nVerify the signature\n"
            + HelpExampleCli("verifymessage", "\"1D1ZrZNe3JUo7ZycKEYQQiQAWd9y54F4XX\" \"signature\" \"my message\"") +
            "\nAs json rpc\n"
            + HelpExampleRpc("verifymessage", "\"1D1ZrZNe3JUo7ZycKEYQQiQAWd9y54F4XX\", \"signature\", \"my message\"")
        );

    LOCK(cs_main);

    std::string strAddress  = request.params[0].get_str();
    std::string strSign     = request.params[1].get_str();
    std::string strMessage  = request.params[2].get_str();

    CTxDestination destination = DecodeDestination(strAddress);
    if (!IsValidDestination(destination)) {
        throw JSONRPCError(RPC_TYPE_ERROR, "Invalid address");
    }

    const CKeyID *keyID = boost::get<CKeyID>(&destination);
    if (!keyID) {
        throw JSONRPCError(RPC_TYPE_ERROR, "Address does not refer to key");
    }

    bool fInvalid = false;
    std::vector<unsigned char> vchSig = DecodeBase64(strSign.c_str(), &fInvalid);

    if (fInvalid)
        throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "Malformed base64 encoding");

    CHashWriter ss(SER_GETHASH, 0);
    ss << strMessageMagic;
    ss << strMessage;

    CPubKey pubkey;
    if (!pubkey.RecoverCompact(ss.GetHash(), vchSig))
        return false;

    return (pubkey.GetID() == *keyID);
}

UniValue signmessagewithprivkey(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 2)
        throw std::runtime_error(
            "signmessagewithprivkey \"privkey\" \"message\"\n"
            "\nSign a message with the private key of an address\n"
            "\nArguments:\n"
            "1. \"privkey\"         (string, required) The private key to sign the message with.\n"
            "2. \"message\"         (string, required) The message to create a signature of.\n"
            "\nResult:\n"
            "\"signature\"          (string) The signature of the message encoded in base 64\n"
            "\nExamples:\n"
            "\nCreate the signature\n"
            + HelpExampleCli("signmessagewithprivkey", "\"privkey\" \"my message\"") +
            "\nVerify the signature\n"
            + HelpExampleCli("verifymessage", "\"1D1ZrZNe3JUo7ZycKEYQQiQAWd9y54F4XX\" \"signature\" \"my message\"") +
            "\nAs json rpc\n"
            + HelpExampleRpc("signmessagewithprivkey", "\"privkey\", \"my message\"")
        );

    std::string strPrivkey = request.params[0].get_str();
    std::string strMessage = request.params[1].get_str();

    CBitcoinSecret vchSecret;
    bool fGood = vchSecret.SetString(strPrivkey);
    if (!fGood)
        throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "Invalid private key");
    CKey key = vchSecret.GetKey();
    if (!key.IsValid())
        throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "Private key outside allowed range");

    CHashWriter ss(SER_GETHASH, 0);
    ss << strMessageMagic;
    ss << strMessage;

    std::vector<unsigned char> vchSig;
    if (!key.SignCompact(ss.GetHash(), vchSig))
        throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "Sign failed");

    return EncodeBase64(vchSig.data(), vchSig.size());
}

UniValue setmocktime(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "setmocktime timestamp\n"
            "\nSet the local time to given timestamp (-regtest only)\n"
            "\nArguments:\n"
            "1. timestamp  (integer, required) Unix seconds-since-epoch timestamp\n"
            "   Pass 0 to go back to using the system time."
        );

    if (!Params().MineBlocksOnDemand())
        throw std::runtime_error("setmocktime for regression testing (-regtest mode) only");

    // For now, don't change mocktime if we're in the middle of validation, as
    // this could have an effect on mempool time-based eviction, as well as
    // IsCurrentForFeeEstimation() and IsInitialBlockDownload().
    // TODO: figure out the right way to synchronize around mocktime, and
    // ensure all call sites of GetTime() are accessing this safely.
    LOCK(cs_main);

    RPCTypeCheck(request.params, {UniValue::VNUM});
    SetMockTime(request.params[0].get_int64());

    return NullUniValue;
}

static UniValue RPCLockedMemoryInfo()
{
    LockedPool::Stats stats = LockedPoolManager::Instance().stats();
    UniValue obj(UniValue::VOBJ);
    obj.pushKV("used", uint64_t(stats.used));
    obj.pushKV("free", uint64_t(stats.free));
    obj.pushKV("total", uint64_t(stats.total));
    obj.pushKV("locked", uint64_t(stats.locked));
    obj.pushKV("chunks_used", uint64_t(stats.chunks_used));
    obj.pushKV("chunks_free", uint64_t(stats.chunks_free));
    return obj;
}

#ifdef HAVE_MALLOC_INFO
static std::string RPCMallocInfo()
{
    char *ptr = nullptr;
    size_t size = 0;
    FILE *f = open_memstream(&ptr, &size);
    if (f) {
        malloc_info(0, f);
        fclose(f);
        if (ptr) {
            std::string rv(ptr, size);
            free(ptr);
            return rv;
        }
    }
    return "";
}
#endif

UniValue getmemoryinfo(const JSONRPCRequest& request)
{
    /* Please, avoid using the word "pool" here in the RPC interface or help,
     * as users will undoubtedly confuse it with the other "memory pool"
     */
    if (request.fHelp || request.params.size() > 1)
        throw std::runtime_error(
            "getmemoryinfo (\"mode\")\n"
            "Returns an object containing information about memory usage.\n"
            "Arguments:\n"
            "1. \"mode\" determines what kind of information is returned. This argument is optional, the default mode is \"stats\".\n"
            "  - \"stats\" returns general statistics about memory usage in the daemon.\n"
            "  - \"mallocinfo\" returns an XML string describing low-level heap state (only available if compiled with glibc 2.10+).\n"
            "\nResult (mode \"stats\"):\n"
            "{\n"
            "  \"locked\": {               (json object) Information about locked memory manager\n"
            "    \"used\": xxxxx,          (numeric) Number of bytes used\n"
            "    \"free\": xxxxx,          (numeric) Number of bytes available in current arenas\n"
            "    \"total\": xxxxxxx,       (numeric) Total number of bytes managed\n"
            "    \"locked\": xxxxxx,       (numeric) Amount of bytes that succeeded locking. If this number is smaller than total, locking pages failed at some point and key data could be swapped to disk.\n"
            "    \"chunks_used\": xxxxx,   (numeric) Number allocated chunks\n"
            "    \"chunks_free\": xxxxx,   (numeric) Number unused chunks\n"
            "  }\n"
            "}\n"
            "\nResult (mode \"mallocinfo\"):\n"
            "\"<malloc version=\"1\">...\"\n"
            "\nExamples:\n"
            + HelpExampleCli("getmemoryinfo", "")
            + HelpExampleRpc("getmemoryinfo", "")
        );

    std::string mode = request.params[0].isNull() ? "stats" : request.params[0].get_str();
    if (mode == "stats") {
        UniValue obj(UniValue::VOBJ);
        obj.pushKV("locked", RPCLockedMemoryInfo());
        return obj;
    } else if (mode == "mallocinfo") {
#ifdef HAVE_MALLOC_INFO
        return RPCMallocInfo();
#else
        throw JSONRPCError(RPC_INVALID_PARAMETER, "mallocinfo is only available when compiled with glibc 2.10+");
#endif
    } else {
        throw JSONRPCError(RPC_INVALID_PARAMETER, "unknown mode " + mode);
    }
}

uint32_t getCategoryMask(UniValue cats) {
    cats = cats.get_array();
    uint32_t mask = 0;
    for (unsigned int i = 0; i < cats.size(); ++i) {
        uint32_t flag = 0;
        std::string cat = cats[i].get_str();
        if (!GetLogCategory(&flag, &cat)) {
            throw JSONRPCError(RPC_INVALID_PARAMETER, "unknown logging category " + cat);
        }
        if (flag == BCLog::NONE) {
            return 0;
        }
        mask |= flag;
    }
    return mask;
}

UniValue logging(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() > 2) {
        throw std::runtime_error(
            "logging ( <include> <exclude> )\n"
            "Gets and sets the logging configuration.\n"
            "When called without an argument, returns the list of categories with status that are currently being debug logged or not.\n"
            "When called with arguments, adds or removes categories from debug logging and return the lists above.\n"
            "The arguments are evaluated in order \"include\", \"exclude\".\n"
            "If an item is both included and excluded, it will thus end up being excluded.\n"
            "The valid logging categories are: " + ListLogCategories() + "\n"
            "In addition, the following are available as category names with special meanings:\n"
            "  - \"all\",  \"1\" : represent all logging categories.\n"
            "  - \"none\", \"0\" : even if other logging categories are specified, ignore all of them.\n"
            "\nArguments:\n"
            "1. \"include\"        (array of strings, optional) A json array of categories to add debug logging\n"
            "     [\n"
            "       \"category\"   (string) the valid logging category\n"
            "       ,...\n"
            "     ]\n"
            "2. \"exclude\"        (array of strings, optional) A json array of categories to remove debug logging\n"
            "     [\n"
            "       \"category\"   (string) the valid logging category\n"
            "       ,...\n"
            "     ]\n"
            "\nResult:\n"
            "{                   (json object where keys are the logging categories, and values indicates its status\n"
            "  \"category\": 0|1,  (numeric) if being debug logged or not. 0:inactive, 1:active\n"
            "  ...\n"
            "}\n"
            "\nExamples:\n"
            + HelpExampleCli("logging", "\"[\\\"all\\\"]\" \"[\\\"http\\\"]\"")
            + HelpExampleRpc("logging", "[\"all\"], \"[libevent]\"")
        );
    }

    uint32_t originalLogCategories = logCategories;
    if (request.params[0].isArray()) {
        logCategories |= getCategoryMask(request.params[0]);
    }

    if (request.params[1].isArray()) {
        logCategories &= ~getCategoryMask(request.params[1]);
    }

    // Update libevent logging if BCLog::LIBEVENT has changed.
    // If the library version doesn't allow it, UpdateHTTPServerLogging() returns false,
    // in which case we should clear the BCLog::LIBEVENT flag.
    // Throw an error if the user has explicitly asked to change only the libevent
    // flag and it failed.
    uint32_t changedLogCategories = originalLogCategories ^ logCategories;
    if (changedLogCategories & BCLog::LIBEVENT) {
        if (!UpdateHTTPServerLogging(logCategories & BCLog::LIBEVENT)) {
            logCategories &= ~BCLog::LIBEVENT;
            if (changedLogCategories == BCLog::LIBEVENT) {
            throw JSONRPCError(RPC_INVALID_PARAMETER, "libevent logging cannot be updated when using libevent before v2.1.1.");
            }
        }
    }

    UniValue result(UniValue::VOBJ);
    std::vector<CLogCategoryActive> vLogCatActive = ListActiveLogCategories();
    for (const auto& logCatActive : vLogCatActive) {
        result.pushKV(logCatActive.category, logCatActive.active);
    }

    return result;
}

UniValue echo(const JSONRPCRequest& request)
{
    if (request.fHelp)
        throw std::runtime_error(
            "echo|echojson \"message\" ...\n"
            "\nSimply echo back the input arguments. This command is for testing.\n"
            "\nThe difference between echo and echojson is that echojson has argument conversion enabled in the client-side table in"
            "freebank-cli and the GUI. There is no server-side difference."
        );

    return request.params;
}

static UniValue getinfo_deprecated(const JSONRPCRequest& request)
{
    throw JSONRPCError(RPC_METHOD_NOT_FOUND,
        "getinfo\n"
        "\nThis call was removed in version 0.16.0. Use the appropriate fields from:\n"
        "- getblockchaininfo: blocks, difficulty, chain\n"
        "- getnetworkinfo: version, protocolversion, timeoffset, connections, proxy, relayfee, warnings\n"
        "- getwalletinfo: balance, keypoololdest, keypoolsize, paytxfee, unlocked_until, walletversion\n"
        "\nfreebank-cli has the option -getinfo to collect and format these in the old format."
    );
}

UniValue refreshbmm(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() < 1 || request.params.size() > 3)
        throw std::runtime_error(
            "refreshbmm\n"
            "\nRefresh automated BMM. Basic testing implementation\n"
            "\nArguments:\n"
            "1. \"amount\"                (numeric) Amount to pay mainchain miner for including BMM request (required)\n"
            "2. \"createnew\" true|false  (bool) Create a new BMM block if possible\n (optional, default: true)\n"
            "3. \"prevblock\"             (string) Hash of sidechain block to build on (optional, default: chaintip)\n"
            "\nResult:\n"
            "hash_last_main_block  (string) Hash of mainchain tip.\n"
            "bmm_block_created     (string) Hash of new BMM block created.\n"
            "bmm_block_submitted   (string) Hash of BMM block connected to sidechain.\n"
            "ntxn                  (number) Number of txn in new BMM request (if created).\n"
            "nfees                 (number) Total fees in new block (if created).\n"
            "txid                  (string) Mainchain BMM request TXID.\n"
            "error                 (string) Output from sidechain client.\n"
        );

    bool fReorg = false;
    std::vector<uint256> vDisconnected;
    if (!UpdateMainBlockHashCache(fReorg, vDisconnected))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to update mainchain block cache!");

    if (fReorg)
        HandleMainchainReorg(vDisconnected);

    CAmount amount = AmountFromValue(request.params[0]);
    if (amount <= 0)
        throw JSONRPCError(RPC_TYPE_ERROR, "Invalid amount for BMM!");

    // Whether or not to create a new BMM block / request if possible. If set
    // false, we will only check for BMM commits in the mainchain and try to
    // connect those blocks but not generate a new BMM block and request.
    bool fCreateNew = request.params.size() >= 2 ? request.params[1].get_bool() : true;

    // If hashPrevBlock is set, we will build a block on top of that block
    // instead of the current sidechain tip.
    uint256 hashPrevBlock;
    if (request.params.size() == 3) {
        LOCK(cs_main);

        hashPrevBlock = uint256S(request.params[2].get_str());
        if (hashPrevBlock.IsNull())
            throw JSONRPCError(RPC_MISC_ERROR, "Invalid prev block hash (null)!");

        // Check if the prevblock is in the side: chain
        if (mapBlockIndex.count(hashPrevBlock) == 0)
            throw JSONRPCError(RPC_MISC_ERROR, "Prev block does not exist!");
    }

    if (!CheckMainchainConnection())
        throw JSONRPCError(RPC_MISC_ERROR, "Must be connected to mainchain (not connected)!");

    SetNetworkActive(true, "refreshbmm RPC command issued");

    SidechainClient client;
    std::string strError = "";
    uint256 hashCreated;
    uint256 hashConnected;
    uint256 hashConnectedBlind;
    uint256 txid;
    int ntxn = 0;
    CAmount nFees = 0;
    if (!client.RefreshBMM(amount, strError, hashCreated, hashConnected, hashConnectedBlind, txid, ntxn, nFees, fCreateNew, hashPrevBlock))
        throw JSONRPCError(RPC_MISC_ERROR, strError);

    UniValue result(UniValue::VOBJ);
    result.pushKV("hash_last_main_block", bmmCache.GetLastMainBlockHash().ToString());
    result.pushKV("bmm_block_created", hashCreated.ToString());
    result.pushKV("bmm_block_submitted", hashConnected.ToString());
    result.pushKV("bmm_block_submitted_blind", hashConnectedBlind.ToString());
    result.pushKV("ntxn", ntxn);
    result.pushKV("nfees", nFees);
    result.pushKV("txid", txid.ToString());
    result.pushKV("error", strError);

    return result;
}

UniValue getaveragemainchainfees(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 2)
        throw std::runtime_error(
            "getaveragemainchainfees\n"
            "\nArguments:\n"
            "1. \"numblocks (numeric, required) the number of blocks to scan\"\n"
            "2. \"startheight (numeric, required) the block height to start scanning at\"\n"
            "\nGet the average transaction fees from the mainchain\n"
            "\nResult:\n"
            "averagefees  (numeric) x.xx\n"
        );

    int nBlocks = request.params[0].get_int();
    int nStartHeight = request.params[1].get_int();

    SidechainClient client;
    CAmount nAverageFees = 0;
    if (!client.GetAverageFees(nBlocks, nStartHeight, nAverageFees))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to request fee average!");

    UniValue result(UniValue::VOBJ);
    result.pushKV("fees", ValueFromAmount(nAverageFees));

    return result;
}

UniValue getmainchainblockcount(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size())
        throw std::runtime_error(
            "getmainchainblockcount\n"
            "\nArguments: none\n"
            "\nGet the mainchain block count\n"
            "\nResult:\n"
            "blockcount  (numeric) x\n"
        );

    SidechainClient client;
    int nBlocks = 0;
    if (!client.GetBlockCount(nBlocks))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to request mainchain height!");

    UniValue result(UniValue::VOBJ);
    result.pushKV("blockcount", nBlocks);

    return result;
}

UniValue getmainchainblockhash(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "getmainchainblockhash\n"
            "\nArguments:\n"
            "1. \"height (numeric, required) the mainchain block height\"\n"
            "\nGet the mainchain block hash\n"
            "\nResult:\n"
            "hashblock  (string)\n"
        );

    int nHeight = request.params[0].get_int();

    SidechainClient client;
    uint256 hashBlock;
    if (!client.GetBlockHash(nHeight, hashBlock))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to request mainchain block hash!");

    UniValue result(UniValue::VOBJ);
    result.pushKV("blockhash", hashBlock.ToString());

    return result;
}

UniValue verifymainblockcache(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size())
        throw std::runtime_error(
            "verifymainblockcache\n"
            "\nArguments: None\n"
            "\nVerify our cache of mainchain block hashes with the mainchain.\n"
            "\nResult:\n"
            "height  (numeric) Cache verified to this mainchain block height.\n"
        );

    std::string strError = "";
    if (!VerifyMainBlockCache(strError))
        throw JSONRPCError(RPC_MISC_ERROR, strError);

    UniValue result(UniValue::VOBJ);
    result.pushKV("height", bmmCache.GetCachedBlockCount() - 1);

    return result;
}

UniValue updatemainblockcache(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size())
        throw std::runtime_error(
            "updatemainblockcache\n"
            "\nArguments: None\n"
            "\nSync our cache of mainchain block hashes with the mainchain.\n"
            "\nResult:\n"
            "reorg          (true/false)\n"
            "disconnected   (numeric)\n"
            "cached         (numeric)\n"
            "cachesize      (numeric)\n"
        );


    int nCached = bmmCache.GetCachedBlockCount();

    bool fReorg = false;
    std::vector<uint256> vDisconnected;
    if (!UpdateMainBlockHashCache(fReorg, vDisconnected))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to update!");

    if (fReorg)
        HandleMainchainReorg(vDisconnected);

    int nCachedResult = bmmCache.GetCachedBlockCount();

    UniValue result(UniValue::VOBJ);
    result.pushKV("reorg", fReorg);
    result.pushKV("disconnected", (uint64_t)vDisconnected.size());
    result.pushKV("cached", nCachedResult - nCached);
    result.pushKV("cachesize", nCachedResult);

    return result;
}

UniValue listmywithdrawals(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size())
        throw std::runtime_error(
            "listmywithdrawals\n"
            "\nArguments: None\n"
            "\nList your sidechain withdrawals.\n"
            "\nResult:\n"
            "id             (string)\n"
        );

    std::set<uint256> setID = bmmCache.GetCachedWithdrawalID();

    UniValue result(UniValue::VARR);
    for (const uint256& u : setID) {
        UniValue obj(UniValue::VOBJ);
        obj.pushKV("id", u.ToString());
        result.push_back(obj);
    }

    return result;
}

UniValue rebroadcastwithdrawalbundle(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size())
        throw std::runtime_error(
            "rebroadcastwithdrawalbundle\n"
            "\nSend the latest WithdrawalBundle transaction hex to the local mainchain node.\n"
        );

    SidechainWithdrawalBundle withdrawalBundle;
    uint256 hashLatest;
    psidechaintree->GetLastWithdrawalBundleHash(hashLatest);

    if (hashLatest.IsNull())
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to lookup latest WithdrawalBundle hash!");

    if (!psidechaintree->GetWithdrawalBundle(hashLatest, withdrawalBundle))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to load latest WithdrawalBundle from database");

    SidechainClient client;
    std::string strHex = EncodeHexTx(withdrawalBundle.tx);
    if (!client.BroadcastWithdrawalBundle(strHex))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to broadcast latest WithdrawalBundle");

    return NullUniValue;
}

UniValue getwithdrawalbundle(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size())
        throw std::runtime_error(
            "getwithdrawalbundle\n"
            "\nGet the latest WithdrawalBundle transaction hex.\n"
        );

    SidechainWithdrawalBundle withdrawalBundle;
    uint256 hashLatest;
    psidechaintree->GetLastWithdrawalBundleHash(hashLatest);

    if (hashLatest.IsNull())
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to lookup latest WithdrawalBundle hash!");

    if (!psidechaintree->GetWithdrawalBundle(hashLatest, withdrawalBundle))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to load latest WithdrawalBundle from database");

    return EncodeHexTx(withdrawalBundle.tx);
}

UniValue getwithdrawal(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "getwithdrawal\n"
            "\nArguments:\n"
            "1. \"id (string, required) the withdrawal ID\"\n"
            "\nGet withdrawal information\n"
        );

    uint256 id = uint256S(request.params[0].get_str());
    if (id.IsNull())
        throw JSONRPCError(RPC_MISC_ERROR, "Invalid ID!");

    SidechainWithdrawal wt;
    if (!psidechaintree->GetWithdrawal(id, wt))
        throw JSONRPCError(RPC_MISC_ERROR, "Withdrawal does not exist!");

    UniValue result(UniValue::VOBJ);
    result.pushKV("destination", wt.strDestination);
    result.pushKV("refunddestination", wt.strRefundDestination);
    result.pushKV("amount", wt.amount);
    result.pushKV("amountmainchainfee",wt.mainchainFee );
    result.pushKV("status", wt.GetStatusStr());
    result.pushKV("hashblindtx", wt.hashBlindTx.ToString());

    return result;
}

UniValue formatdepositaddress(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "formatdepositaddress \"address\"\n"
            "\nTakes any string and returns a sidechain deposit address\n"
            "Use this command to turn a sidechain receiving address into a deposit address.\n"
            "\nArguments:\n"
            "1. \"address\"      (string, required) The destination to be formatted as a deposit address\n"
            "\nResult:\n"
            "deposit address\n"
            "\nExamples:\n"
            + HelpExampleCli("formatdepositaddress", "\"1PSSGeFHDnKNxiEyFrD1wcEaHr9hrQDDWc\"")
            + HelpExampleRpc("formatdepositaddress", "\"1PSSGeFHDnKNxiEyFrD1wcEaHr9hrQDDWc\"")
        );

    std::string strAddress = request.params[0].get_str();
    if (strAddress.empty())
        throw JSONRPCError(RPC_MISC_ERROR, "Input is blank!");


    std::string strDepositAddress = GenerateDepositAddress(strAddress);
    std::string strAddressOut = "";
    unsigned int nSidechainOut;
    if (!ParseDepositAddress(strDepositAddress, strAddressOut, nSidechainOut))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to verify deposit address!");

    return strDepositAddress;
}

UniValue listassets(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size())
        throw std::runtime_error(
            "listassets\n"
            "\nList BitAssets\n"
            "\nResult:\n"
            "Array of BitAssets\n"
            "\nExamples:\n"
            + HelpExampleCli("listassets", "")
            + HelpExampleRpc("listassets", "")
        );

    std::vector<BitAsset> vAsset = passettree->GetAssets();

    UniValue result(UniValue::VARR);
    for (const BitAsset& b : vAsset) {
        UniValue obj(UniValue::VOBJ);
        obj.pushKV("id", (uint64_t)b.nID);
        obj.pushKV("ticker", b.strTicker);
        obj.pushKV("supply", b.nSupply);
        obj.pushKV("headline", b.strHeadline);
        obj.pushKV("payload", b.payload.ToString());
        obj.pushKV("txid", b.txid.ToString());
        obj.pushKV("controller", b.strController);
        obj.pushKV("owner", b.strOwner);
        result.push_back(obj);
    }

    return result;
}

static UniValue BillToJSON(const CBill& bill, bool fIncludeBody)
{
    UniValue obj(UniValue::VOBJ);
    obj.pushKV("id", (uint64_t)bill.nBillID);
    obj.pushKV("bill_id", bill.billID.ToString());
    obj.pushKV("amount", ValueFromAmount(bill.amount));
    obj.pushKV("amount_grams", GramsUV((int64_t)bill.amount));
    obj.pushKV("escrow", ValueFromAmount(bill.amountEscrow));
    obj.pushKV("escrow_grams", GramsUV((int64_t)bill.amountEscrow));
    obj.pushKV("status", std::string(1, bill.status));
    obj.pushKV("issued_height", (uint64_t)bill.nIssuedHeight);
    obj.pushKV("maturity_height", (uint64_t)bill.nMaturityHeight);
    obj.pushKV("grace_blocks", (uint64_t)bill.nGraceBlocks);
    obj.pushKV("drawer_pubkey", HexStr(bill.vchDrawerPubKey));
    obj.pushKV("acceptor_pubkey", HexStr(bill.vchAcceptorPubKey));
    obj.pushKV("holder_pubkey", HexStr(bill.vchHolderPubKey));
    obj.pushKV("issue_txid", bill.txidIssue.ToString());
    obj.pushKV("escrow_outpoint", bill.outEscrow.hash.ToString() + ":" + itostr(bill.outEscrow.n));
    obj.pushKV("title_outpoint", bill.outTitle.hash.ToString() + ":" + itostr(bill.outTitle.n));

    UniValue endorsements(UniValue::VARR);
    for (const BillEndorsement& e : bill.vEndorsement) {
        UniValue eo(UniValue::VOBJ);
        eo.pushKV("from", HexStr(e.vchFrom));
        eo.pushKV("to", HexStr(e.vchTo));
        eo.pushKV("at_height", (uint64_t)e.nAtHeight);
        endorsements.push_back(eo);
    }
    obj.pushKV("endorsements", endorsements);

    if (fIncludeBody)
        obj.pushKV("encrypted_body", HexStr(bill.vchEncryptedBody));

    return obj;
}

UniValue listbills(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 0)
        throw std::runtime_error(
            "listbills\n"
            "List all bills of exchange tracked by the node\n"
            "\nResult (array of bill objects)\n"
            "\nExamples:\n"
            + HelpExampleCli("listbills", "")
            + HelpExampleRpc("listbills", "")
        );

    LOCK(cs_main);

    UniValue ret(UniValue::VARR);
    for (const CBill& bill : pbilltree->GetBills())
        ret.push_back(BillToJSON(bill, false /* fIncludeBody */));

    return ret;
}

UniValue getbill(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "getbill\n"
            "\nArguments:\n"
            "1. id            (numeric, required) the bill ID number\n"
            "\nGet one bill of exchange (full record incl. encrypted body)\n"
            "\nExamples:\n"
            + HelpExampleCli("getbill", "1")
            + HelpExampleRpc("getbill", "1")
        );

    const uint32_t nBillID = request.params[0].get_int();

    LOCK(cs_main);

    CBill bill;
    if (!pbilltree->GetBill(nBillID, bill))
        throw JSONRPCError(RPC_MISC_ERROR, "Unknown bill!");

    return BillToJSON(bill, true /* fIncludeBody */);
}


static UniValue HouseToJSON(const CHouse& house)
{
    UniValue obj(UniValue::VOBJ);
    obj.pushKV("id", (uint64_t)house.nHouseID);
    obj.pushKV("househash", house.houseID.ToString());
    obj.pushKV("tier", house.nTier);
    obj.pushKV("threshold", (uint64_t)house.nThresholdM);
    obj.pushKV("classid", house.strClassID);
    obj.pushKV("denominationmggold", house.nDenomMgGold);
    obj.pushKV("lambdax10", (uint64_t)HOUSE_LAMBDA_X10[house.nTier <= MAX_HOUSE_TIER ? house.nTier : 0]);
    obj.pushKV("activeescrow", ValueFromAmount(house.ActiveEscrow()));
    obj.pushKV("activeescrow_grams", GramsUV((int64_t)house.ActiveEscrow()));
    obj.pushKV("mintedunits", house.nMintedUnits);
    obj.pushKV("mintedunits_grams", GramsUV((int64_t)house.nMintedUnits));
    // Term-deposit accounting (Phase 3.8): the D in the shared cap N + D <=
    // lambda*E, and the weighted-average REMAINING term (blocks) of the deposit
    // book - the market's view of the maturity profile (a full bucketed ladder
    // lands with the wallet in T-i10). match_funding is the attestation-checked
    // long-vs-short rule (vacuously true in v1 - no loan book yet).
    obj.pushKV("depositunits", house.nDepositUnits);
    obj.pushKV("depositwam", (uint64_t)HouseDepositWAM(house, chainActive.Height() + 1));
    obj.pushKV("matchfundingok", HouseMatchFundingOK(house, chainActive.Height() + 1));
    // Raw weighted-maturity accumulator (Sigma principal*maturity), the two u64
    // words of the 128-bit value. Height-independent house state - the reorg gate
    // folds these into its canonical signature so a DisconnectBlock undo of a
    // deposit op is checked byte-exact, not just via the depositunits counter.
    obj.pushKV("depositwtmathi", house.nDepositWtMatHi);
    obj.pushKV("depositwtmatlo", house.nDepositWtMatLo);
    obj.pushKV("insolventdepositprincipal", house.nInsolventDepositPrincipal);
    // The BINDING cap is the min of the two (3.5 D2): capital (lambda*escrow)
    // and reserve (attested till / rho). Publish all three - the market prices
    // which constraint is binding.
    obj.pushKV("mintcapunits", HouseMintCapUnits(house));
    obj.pushKV("mintcapunits_grams", GramsUV((int64_t)HouseMintCapUnits(house)));
    obj.pushKV("capitalcapunits", HouseCapitalCapUnits(house));
    obj.pushKV("reservecapunits", HouseReserveCapUnits(house));
    // The attested ratio and the redemption spread it implies (3.5). Published
    // so a holder can see the cost of the exit BEFORE they take it - the whole
    // deterrent depends on the fee being known ex ante.
    obj.pushKV("attestedratiobps", (uint64_t)HouseAttestedRatioBps(house));
    obj.pushKV("brassagebps", (uint64_t)HouseBrassageBps(house));

    static const auto StatusName = [](char s) -> std::string {
        if (s == HOUSE_STATUS_OPEN) return "open";
        if (s == HOUSE_STATUS_STRESSED) return "stressed";
        if (s == HOUSE_STATUS_DEFERRED) return "deferred";
        if (s == HOUSE_STATUS_INSOLVENT) return "insolvent";
        if (s == HOUSE_STATUS_WOUNDDOWN) return "wounddown";
        return "unknown";
    };
    obj.pushKV("status", StatusName(house.status));
    // The consensus-operative status at the current tip (3.4): stressed /
    // insolvent are usually DERIVED (missed cadence, window expiry), not
    // stored - display must not go stale between transitions and txs.
    {
        const int nTipHeight = chainActive.Height();
        obj.pushKV("effective_status", StatusName(HouseEffectiveStatus(house, nTipHeight)));
        uint32_t nStress = house.nStressSinceHeight;
        const uint32_t nDeadline = house.nLastAttestHeight + HOUSE_ATTEST_MISS_N * HOUSE_ATTEST_CADENCE;
        if ((uint32_t)nTipHeight > nDeadline && (nStress == 0 || nDeadline + 1 < nStress))
            nStress = nDeadline + 1;
        if (nStress != 0)
            obj.pushKV("stress_since", (uint64_t)nStress);
        obj.pushKV("attest_deadline", (uint64_t)nDeadline);
        obj.pushKV("lastattestheight", (uint64_t)house.nLastAttestHeight);
        obj.pushKV("lastattestreserves", ValueFromAmount(house.amountLastAttestReserves));
        obj.pushKV("lastattestreserves_grams", GramsUV((int64_t)house.amountLastAttestReserves));
        if (house.nInsolventHeight != 0) {
            obj.pushKV("insolventheight", (uint64_t)house.nInsolventHeight);
            obj.pushKV("insolventunits", house.nInsolventUnits);
            obj.pushKV("insolventpot", ValueFromAmount(house.amountInsolventPot));
        }
        obj.pushKV("escrowchangeoutputs", (uint64_t)house.vOutEscrowChange.size());
        obj.pushKV("reservelockoutputs", (uint64_t)house.vOutReserveLock.size());
        // Option-clause state (3.5). The confidence-death counters are
        // published deliberately: CD is a guard, not a kill switch, so the
        // MARKET is what prices a house that keeps reaching for the clause.
        if (house.nDeferInvokedHeight != 0) {
            obj.pushKV("defer_invoked_height", (uint64_t)house.nDeferInvokedHeight);
            obj.pushKV("defer_end_height", (uint64_t)house.DeferEndHeight());
        }
        obj.pushKV("defer_renewals", (uint64_t)house.nDeferRenewals);
        obj.pushKV("defer_activations", (uint64_t)house.nDeferActivations);
        // DR-2: the height the most recent episode ended (recovery), 0 if none.
        // Interest on a demanded note accrues demand -> this height, not to the
        // eventual redemption.
        obj.pushKV("defer_ended_height", (uint64_t)house.nDeferEndedHeight);
        obj.pushKV("defer_suspended_blocks", (uint64_t)house.DeferSuspendedBlocks(nTipHeight));
        obj.pushKV("confidence_dead", HouseConfidenceDead(house, nTipHeight));
    }
    obj.pushKV("registeredheight", (uint64_t)house.nRegisteredHeight);
    obj.pushKV("txidregister", house.txidRegister.ToString());

    UniValue partners(UniValue::VARR);
    for (size_t i = 0; i < house.vPartner.size(); i++) {
        const HousePartner& p = house.vPartner[i];
        UniValue po(UniValue::VOBJ);
        po.pushKV("index", (uint64_t)i);
        po.pushKV("pubkey", HexStr(p.vchPubKey));
        po.pushKV("pledge", ValueFromAmount(p.amountPledge));
        po.pushKV("status", p.status == HOUSE_PARTNER_ACTIVE ? "active"
                          : p.status == HOUSE_PARTNER_SETTLED ? "settled" : "tail");
        if (p.status == HOUSE_PARTNER_TAIL)
            po.pushKV("tailunlockheight", (uint64_t)p.nTailUnlockHeight);
        po.pushKV("pledgeoutputs", (uint64_t)p.vOutPledge.size());
        partners.push_back(po);
    }
    obj.pushKV("partners", partners);
    return obj;
}

UniValue listhouses(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 0)
        throw std::runtime_error(
            "listhouses\n"
            "List all discount houses tracked by the node\n"
            "\nResult (array of house objects)\n"
            "\nExamples:\n"
            + HelpExampleCli("listhouses", "")
            + HelpExampleRpc("listhouses", "")
        );

    LOCK(cs_main);

    UniValue ret(UniValue::VARR);
    for (const CHouse& house : phousetree->GetHouses())
        ret.push_back(HouseToJSON(house));

    return ret;
}

UniValue gethouse(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "gethouse\n"
            "\nArguments:\n"
            "1. id            (numeric, required) the house ID number\n"
            "\nGet one discount house (full record incl. partner set)\n"
            "\nExamples:\n"
            + HelpExampleCli("gethouse", "1")
            + HelpExampleRpc("gethouse", "1")
        );

    const uint32_t nHouseID = request.params[0].get_int();

    LOCK(cs_main);

    CHouse house;
    if (!phousetree->GetHouse(nHouseID, house))
        throw JSONRPCError(RPC_MISC_ERROR, "Unknown house!");

    return HouseToJSON(house);
}

static UniValue PoolToJSON(const CPool& pool)
{
    UniValue obj(UniValue::VOBJ);
    obj.pushKV("pool_id", (uint64_t)pool.nPoolID);
    obj.pushKV("house_id", (uint64_t)pool.nPoolID);   // v1 invariant: one pool per house
    obj.pushKV("fee_bps", (uint64_t)pool.nFeeBps);
    obj.pushKV("note_reserve", pool.nNoteReserve);
    obj.pushKV("note_reserve_grams", GramsUV((int64_t)pool.nNoteReserve));
    obj.pushKV("btx_reserve", pool.amountBtxReserve);
    obj.pushKV("btx_reserve_grams", GramsUV((int64_t)pool.amountBtxReserve));
    obj.pushKV("lp_supply", pool.nLpSupply);
    obj.pushKV("locked_lp", POOL_MIN_LIQUIDITY);
    // Spot price of one note unit in sats, scaled by 1e8 for precision
    // (informational; the executable price includes the fee + impact).
    if (pool.nNoteReserve > 0) {
        const unsigned __int128 px = (unsigned __int128)(uint64_t)pool.amountBtxReserve
                                   * (unsigned __int128)100000000 / (unsigned __int128)pool.nNoteReserve;
        obj.pushKV("spot_price_sats_x1e8", (uint64_t)px);
    }
    obj.pushKV("note_escrow_txid", pool.outNote.hash.ToString());
    obj.pushKV("note_escrow_vout", (uint64_t)pool.outNote.n);
    obj.pushKV("btx_escrow_txid", pool.outBtx.hash.ToString());
    obj.pushKV("btx_escrow_vout", (uint64_t)pool.outBtx.n);
    obj.pushKV("createheight", (uint64_t)pool.nCreateHeight);
    return obj;
}

UniValue listpools(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 0)
        throw std::runtime_error(
            "listpools\n"
            "List all note<->BTX AMM pools tracked by the node\n"
            "\nResult (array of pool objects)\n"
            "\nExamples:\n"
            + HelpExampleCli("listpools", "")
            + HelpExampleRpc("listpools", "")
        );

    LOCK(cs_main);

    UniValue ret(UniValue::VARR);
    for (const CPool& pool : ppooltree->GetPools())
        ret.push_back(PoolToJSON(pool));

    return ret;
}

UniValue getpool(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "getpool\n"
            "\nArguments:\n"
            "1. id            (numeric, required) the pool ID (== the house ID)\n"
            "\nGet one AMM pool (reserves, LP supply, fee, custody outpoints)\n"
            "\nExamples:\n"
            + HelpExampleCli("getpool", "1")
            + HelpExampleRpc("getpool", "1")
        );

    const uint32_t nPoolID = request.params[0].get_int();

    LOCK(cs_main);

    CPool pool;
    if (!ppooltree->GetPool(nPoolID, pool))
        throw JSONRPCError(RPC_MISC_ERROR, "Unknown pool!");

    return PoolToJSON(pool);
}

UniValue getgramrate(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 0)
        throw std::runtime_error(
            "getgramrate\n"
            "Report the launch presentation scale (satoshis per gram of gold).\n"
            "PRESENTATION ONLY: redemption is fixed at par in ECX and this scale\n"
            "is NOT consensus-enforced.\n"
            "\nResult:\n"
            "{\n"
            "  \"sats_per_gram\": n,   (numeric) satoshis representing one gram of gold\n"
            "  \"grams_per_ecx\": n,   (numeric) grams of gold per 1 ECX (1e8 / sats_per_gram)\n"
            "  \"disclaimer\": \"x\"     (string) presentation-scale caveat\n"
            "}\n"
            "\nExamples:\n"
            + HelpExampleCli("getgramrate", "")
            + HelpExampleRpc("getgramrate", "")
        );

    UniValue ret(UniValue::VOBJ);
    ret.pushKV("sats_per_gram", g_launchSatsPerGram);
    ret.pushKV("grams_per_ecx", GramsFromSats(COIN));
    ret.pushKV("disclaimer",
               "launch presentation scale; redemption is fixed ECX; NOT consensus-enforced");
    return ret;
}

static const CRPCCommand commands[] =
{ //  category              name                        actor (function)           argNames
  //  --------------------- ------------------------    -----------------------    ----------
    { "control",            "getmemoryinfo",            &getmemoryinfo,            {"mode"} },
    { "control",            "logging",                  &logging,                  {"include", "exclude"}},
    { "util",               "validateaddress",          &validateaddress,          {"address"} }, /* uses wallet if enabled */
    { "util",               "createmultisig",           &createmultisig,           {"nrequired","keys"} },
    { "util",               "verifymessage",            &verifymessage,            {"address","signature","message"} },
    { "util",               "signmessagewithprivkey",   &signmessagewithprivkey,   {"privkey","message"} },

    /* Not shown in help */
    { "hidden",             "setmocktime",              &setmocktime,              {"timestamp"}},
    { "hidden",             "echo",                     &echo,                     {"arg0","arg1","arg2","arg3","arg4","arg5","arg6","arg7","arg8","arg9"}},
    { "hidden",             "echojson",                 &echo,                     {"arg0","arg1","arg2","arg3","arg4","arg5","arg6","arg7","arg8","arg9"}},
    { "hidden",             "getinfo",                  &getinfo_deprecated,       {}},

    /* Sidechain RPC functions */
    { "sidechain",          "refreshbmm",                   &refreshbmm,                    {"amount", "createnew", "prevblock"}},
    { "sidechain",          "getaveragemainchainfees",      &getaveragemainchainfees,       {"blockcount", "startheight"}},
    { "sidechain",          "getmainchainblockcount",       &getmainchainblockcount,        {}},
    { "sidechain",          "getmainchainblockhash",        &getmainchainblockhash,         {"height"}},
    { "sidechain",          "getwithdrawalbundle",          &getwithdrawalbundle,           {}},
    { "sidechain",          "verifymainblockcache",         &verifymainblockcache,          {}},
    { "sidechain",          "updatemainblockcache",         &updatemainblockcache,          {}},
    { "sidechain",          "listmywithdrawals",            &listmywithdrawals,             {}},
    { "sidechain",          "rebroadcastwithdrawalbundle",  &rebroadcastwithdrawalbundle,   {}},
    { "sidechain",          "getwithdrawal",                &getwithdrawal,                 {"id"}},
    { "sidechain",          "formatdepositaddress",         &formatdepositaddress,          {"address"}},

    { "bills",              "listbills",                    &listbills,                     {}},
    { "bills",              "getbill",                      &getbill,                       {"id"}},

    { "houses",             "listhouses",                   &listhouses,                    {}},
    { "houses",             "gethouse",                     &gethouse,                      {"id"}},

    { "pools",              "listpools",                    &listpools,                     {}},
    { "pools",              "getpool",                      &getpool,                       {"id"}},

    { "freebank",           "getgramrate",                  &getgramrate,                   {}},

    /* BitAssets */
    { "BitAssets",          "listassets",                   &listassets,                    {}},
};

void RegisterMiscRPCCommands(CRPCTable &t)
{
    for (unsigned int vcidx = 0; vcidx < ARRAYLEN(commands); vcidx++)
        t.appendCommand(commands[vcidx].name, &commands[vcidx]);
}
